apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cliente
  template:
    metadata:
      labels:
        app: ms-cliente
    spec:
      containers: 
        - name: ms-cliente
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/ms-cliente:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "124Mi"
              cpu: "0.25"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
      restartPolicy: Always