apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-cliente
spec:
  provider: aws
  secretObjects:
  - data:
    - key: urlCustomers
      objectName: urlCustomers
    secretName: documentdb-secret
    type: Opaque
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:documentdbcredentialsv2-0tW5zl"
          objectType: "secretsmanager"
          jmesPath:
            - path: "urlCustomers"
              objectAlias: "urlCustomers"
