apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-cliente
spec:
  provider: aws
  secretObjects:
  - data:
    - key: urlCustomers
      objectName: documentdbcredentials
    secretName: documentdb-secret
    type: Opaque
  parameters:
    objects: |
        - objectName: "documentdbcredentials"
          objectType: "secretsmanager"