apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-cliente
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:documentdbcredentials-spRhe0"
          objectType: "secretsmanager"
          objectAlias: "documentdbcredentials"